env:
  browser: true
  node: true
  es2020: true
  mocha: true
globals:
  expect: false
  Cypress: false
  cy: false
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins:
  - unicorn
rules:
  unicorn/no-abusive-eslint-disable: error
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
